### ISSUE TITLE
Help to make it work

### ISSUE THREAD

**Issue by userMak** [bernikr/lovelace-webos-keyboard#2]
hi
I just installed your card which seems very interesting. however can you tell me how it suppose to work?
my tv is turned on, I am writing a message in ha and hit enter.. I don't see any messages.
what am I doing wrong?
Thanks!

**Comment by bernikr** [comment]
This card is for typing on the webOS TV onscreen keyboard (for example in the settings).

If you want to send a notification to the TV look at my other card: [bernikr/lovelace-notify-card](https://github.com/bernikr/lovelace-notify-card)

**Comment by userMak** [comment]
thanks. if I add the notify card where these notifications will appear? for example if someone is watching live tv will the notification appear in the TV of if they watching Netflix ?

**Comment by bernikr** [comment]
The notifications always appear in the the upper right corner of the
screen. It doesn't matter what content is watched. (Live TV, Apps and other
sources all work)

**Comment by userMak** [comment]
Yes just test it. it is working fine, but each notification stays (Toast’ type) for 5 sec only unfortunately. I read somewhere that probably we should send alert type notifications but I don't think this is doable at the moment. Is it?

**Comment by bernikr** [comment]
I think that is not possible, at least in the [docs of the webOS TV integration](https://www.home-assistant.io/integrations/webostv/#notifications) nothing is mentioned.

**Comment by userMak** [comment]
yes it is a pity, it would be much more useful 
in any case, thanks I like it a lot.
