### ISSUE TITLE
HTML Div Renders 0px Height

### ISSUE THREAD

**Issue by njobrien1006** [bernikr/lovelace-webos-keyboard#3]
I've been using the card for a couple of years. A couple months back the ability to put text in, was no longer possible.

The Flex Div or paper-input is rendering to 0 pixels tall. I believe HA must have changed something in the rendering scheme.

Issue present on HA 2024.01.03 via Edge, Chrome and iPhone-IOS-App:

![2024-01-13_13-25-08](https://github.com/bernikr/lovelace-webos-keyboard-card/assets/59174199/977d62a9-b38d-4797-9b36-5bf05af9e57b)

**Comment by bernikr** [comment]
I published an update, can you try if it resolves the issue?

**Comment by njobrien1006** [comment]
Thank you for the prompt update. Yes. Resolved.

Closes #3

![2024-01-13_15-01-57](https://github.com/bernikr/lovelace-webos-keyboard-card/assets/59174199/06a1f450-e09d-4a38-82da-dd051e97f466)
